export const LIST_TYPES = {
  FETCH_LISTS_REQUEST: 'FETCH_LISTS_REQUEST',
  FETCH_LISTS_SUCCESS: 'FETCH_LISTS_SUCCESS',
  FETCH_LISTS_FAILURE: 'FETCH_LISTS_FAILURE',
  SELECT_LIST: 'SELECT_LIST',
  MOVE_ITEM: 'MOVE_ITEM',
  SET_CREATING_LIST: 'SET_CREATING_LIST',
  CANCEL_CHANGES: 'CANCEL_CHANGES',
  UPDATE_CHANGES: 'UPDATE_CHANGES'
} 